default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "23.3.0"
    hooks:
      - id: black
        args:
          - --line-length=160
          - --include='\.py'
        stages: [commit, manual]
        types: [python]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        stages: [commit, manual]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.270"
    hooks:
      - id: ruff
        args:
          - --line-length=160
          # - --fix
        stages: [commit, manual]
